[workspace]
resolver = "2"
members = [
    "crates/redbookmaster-lib",
    "crates/redbookmaster-cli",
    "crates/redbookmaster-gui",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Mathias Karstaedt"]
license = "MIT"
repository = "https://github.com/webmatze/redbookmaster"

[profile.release]
lto = true
codegen-units = 1
strip = true
