// CUE sheet generation
// Creates standard CUE files with CD-TEXT support

use std::io::Write;
use std::path::Path;

use crate::core::{Album, track::{duration_to_frames, FRAMES_PER_SECOND}};

/// Generate a CUE sheet for the album
pub fn generate_cue(album: &Album, wav_filename: &str, output: &Path) -> Result<(), CueError> {
    let mut file = std::fs::File::create(output)
        .map_err(|e| CueError::WriteError(output.to_path_buf(), e.to_string()))?;

    // Write header comments
    writeln!(file, "REM Generated by Red Book Master")?;
    writeln!(file, "REM DATE {}", chrono::Utc::now().format("%Y-%m-%d"))?;
    writeln!(file)?;

    // Album metadata
    if let Some(ref catalog) = album.catalog {
        writeln!(file, "CATALOG {}", catalog)?;
    }

    writeln!(file, "PERFORMER \"{}\"", escape_cue_string(&album.performer))?;
    writeln!(file, "TITLE \"{}\"", escape_cue_string(&album.title))?;

    if let Some(ref songwriter) = album.songwriter {
        writeln!(file, "SONGWRITER \"{}\"", escape_cue_string(songwriter))?;
    }

    writeln!(file)?;

    // Single WAV file reference
    writeln!(file, "FILE \"{}\" WAVE", wav_filename)?;

    // Calculate cumulative position
    let mut current_frame: u32 = 0;

    for track in &album.tracks {
        writeln!(file, "  TRACK {:02} AUDIO", track.number)?;

        // Track metadata
        writeln!(file, "    TITLE \"{}\"", escape_cue_string(&track.title))?;

        let performer = track
            .performer
            .as_ref()
            .unwrap_or(&album.performer);
        writeln!(file, "    PERFORMER \"{}\"", escape_cue_string(performer))?;

        if let Some(ref songwriter) = track.songwriter.as_ref().or(album.songwriter.as_ref()) {
            writeln!(file, "    SONGWRITER \"{}\"", escape_cue_string(songwriter))?;
        }

        if let Some(ref isrc) = track.isrc {
            writeln!(file, "    ISRC {}", isrc.as_str())?;
        }

        // INDEX 00 (pregap) if there's a pregap
        if track.pregap.as_millis() > 0 {
            writeln!(file, "    INDEX 00 {}", format_cue_time(current_frame))?;
            current_frame += duration_to_frames(track.pregap);
        }

        // INDEX 01 (track start)
        writeln!(file, "    INDEX 01 {}", format_cue_time(current_frame))?;

        // Move position past the track audio
        current_frame += duration_to_frames(track.duration);

        // Add postgap if present
        if track.postgap.as_millis() > 0 {
            writeln!(file, "    POSTGAP {}", format_cue_time(duration_to_frames(track.postgap)))?;
        }
    }

    Ok(())
}

/// Generate a CUE sheet with separate files for each track
pub fn generate_cue_multi(album: &Album, output: &Path) -> Result<(), CueError> {
    let mut file = std::fs::File::create(output)
        .map_err(|e| CueError::WriteError(output.to_path_buf(), e.to_string()))?;

    // Write header
    writeln!(file, "REM Generated by Red Book Master")?;
    writeln!(file, "REM DATE {}", chrono::Utc::now().format("%Y-%m-%d"))?;
    writeln!(file)?;

    // Album metadata
    if let Some(ref catalog) = album.catalog {
        writeln!(file, "CATALOG {}", catalog)?;
    }

    writeln!(file, "PERFORMER \"{}\"", escape_cue_string(&album.performer))?;
    writeln!(file, "TITLE \"{}\"", escape_cue_string(&album.title))?;

    if let Some(ref songwriter) = album.songwriter {
        writeln!(file, "SONGWRITER \"{}\"", escape_cue_string(songwriter))?;
    }

    writeln!(file)?;

    for track in &album.tracks {
        // File reference for this track
        let filename = track.source_file
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("track.wav");

        writeln!(file, "FILE \"{}\" WAVE", filename)?;
        writeln!(file, "  TRACK {:02} AUDIO", track.number)?;

        // Track metadata
        writeln!(file, "    TITLE \"{}\"", escape_cue_string(&track.title))?;

        let performer = track.performer.as_ref().unwrap_or(&album.performer);
        writeln!(file, "    PERFORMER \"{}\"", escape_cue_string(performer))?;

        if let Some(ref isrc) = track.isrc {
            writeln!(file, "    ISRC {}", isrc.as_str())?;
        }

        // Pregap for track 1
        if track.number == 1 && track.pregap.as_millis() > 0 {
            writeln!(file, "    PREGAP {}", format_cue_time(duration_to_frames(track.pregap)))?;
        }

        // INDEX 01 at start of file
        writeln!(file, "    INDEX 01 00:00:00")?;
    }

    Ok(())
}

/// Format a frame count as CUE time (MM:SS:FF)
fn format_cue_time(frames: u32) -> String {
    let ff = frames % FRAMES_PER_SECOND;
    let total_seconds = frames / FRAMES_PER_SECOND;
    let ss = total_seconds % 60;
    let mm = total_seconds / 60;
    format!("{:02}:{:02}:{:02}", mm, ss, ff)
}

/// Escape special characters in CUE strings
fn escape_cue_string(s: &str) -> String {
    s.replace('\"', "\\\"")
}

#[derive(Debug, thiserror::Error)]
pub enum CueError {
    #[error("Failed to write CUE file '{0}': {1}")]
    WriteError(std::path::PathBuf, String),

    #[error("IO error: {0}")]
    IoError(#[from] std::io::Error),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_cue_time() {
        assert_eq!(format_cue_time(0), "00:00:00");
        assert_eq!(format_cue_time(75), "00:01:00");
        assert_eq!(format_cue_time(150), "00:02:00");
        assert_eq!(format_cue_time(4500), "01:00:00");
        assert_eq!(format_cue_time(4537), "01:00:37");
    }

    #[test]
    fn test_escape_cue_string() {
        assert_eq!(escape_cue_string("Hello World"), "Hello World");
        assert_eq!(escape_cue_string("Say \"Hello\""), "Say \\\"Hello\\\"");
    }
}
