// TOC file generation for cdrdao
// Creates TOC files compatible with cdrdao disc-at-once burning

use std::io::Write;
use std::path::Path;

use crate::core::{Album, track::{duration_to_frames, format_duration_msf, FRAMES_PER_SECOND}};

/// Generate a TOC file for cdrdao
pub fn generate_toc(album: &Album, wav_filename: &str, output: &Path) -> Result<(), TocError> {
    let mut file = std::fs::File::create(output)
        .map_err(|e| TocError::WriteError(output.to_path_buf(), e.to_string()))?;

    // Header
    writeln!(file, "// Generated by Red Book Master")?;
    writeln!(file, "// {}", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC"))?;
    writeln!(file)?;

    // CD-DA mode
    writeln!(file, "CD_DA")?;
    writeln!(file)?;

    // CD-TEXT block if we have metadata
    if has_cd_text(album) {
        writeln!(file, "CD_TEXT {{")?;
        writeln!(file, "  LANGUAGE_MAP {{")?;
        writeln!(file, "    0: EN")?;
        writeln!(file, "  }}")?;
        writeln!(file)?;
        writeln!(file, "  LANGUAGE 0 {{")?;
        writeln!(file, "    TITLE \"{}\"", escape_toc_string(&album.title))?;
        writeln!(file, "    PERFORMER \"{}\"", escape_toc_string(&album.performer))?;
        if let Some(ref songwriter) = album.songwriter {
            writeln!(file, "    SONGWRITER \"{}\"", escape_toc_string(songwriter))?;
        }
        writeln!(file, "  }}")?;
        writeln!(file, "}}")?;
        writeln!(file)?;
    }

    // Catalog number
    if let Some(ref catalog) = album.catalog {
        writeln!(file, "CATALOG \"{}\"", catalog)?;
        writeln!(file)?;
    }

    // Calculate positions
    let mut current_frame: u32 = 0;

    for track in &album.tracks {
        writeln!(file, "// Track {}: {}", track.number, track.title)?;
        writeln!(file, "TRACK AUDIO")?;

        // CD-TEXT for this track
        if has_track_cd_text(track, album) {
            writeln!(file, "  CD_TEXT {{")?;
            writeln!(file, "    LANGUAGE 0 {{")?;
            writeln!(file, "      TITLE \"{}\"", escape_toc_string(&track.title))?;
            let performer = track.performer.as_ref().unwrap_or(&album.performer);
            writeln!(file, "      PERFORMER \"{}\"", escape_toc_string(performer))?;
            if let Some(ref songwriter) = track.songwriter.as_ref().or(album.songwriter.as_ref()) {
                writeln!(file, "      SONGWRITER \"{}\"", escape_toc_string(songwriter))?;
            }
            writeln!(file, "    }}")?;
            writeln!(file, "  }}")?;
        }

        // ISRC
        if let Some(ref isrc) = track.isrc {
            writeln!(file, "  ISRC \"{}\"", isrc.as_str())?;
        }

        // Pregap (silence before track)
        if track.pregap.as_millis() > 0 {
            let pregap_msf = format_duration_msf(track.pregap);
            writeln!(file, "  PREGAP {}", pregap_msf)?;
        }

        // Audio file with start and length
        let start_msf = format_duration_msf(frames_to_duration(current_frame));
        let length_msf = format_duration_msf(track.duration);
        writeln!(file, "  FILE \"{}\" {} {}", wav_filename, start_msf, length_msf)?;

        // Postgap
        if track.postgap.as_millis() > 0 {
            let postgap_msf = format_duration_msf(track.postgap);
            writeln!(file, "  POSTGAP {}", postgap_msf)?;
        }

        writeln!(file)?;

        // Update position
        current_frame += duration_to_frames(track.pregap);
        current_frame += duration_to_frames(track.duration);
        current_frame += duration_to_frames(track.postgap);
    }

    Ok(())
}

/// Check if album has any CD-TEXT data worth writing
fn has_cd_text(album: &Album) -> bool {
    !album.title.is_empty() || !album.performer.is_empty() || album.songwriter.is_some()
}

/// Check if track has any CD-TEXT data
fn has_track_cd_text(track: &crate::core::Track, album: &Album) -> bool {
    !track.title.is_empty()
        || track.performer.is_some()
        || track.songwriter.is_some()
        || !album.performer.is_empty()
}

/// Convert frames to Duration
fn frames_to_duration(frames: u32) -> std::time::Duration {
    let millis = (frames as u64 * 1000) / FRAMES_PER_SECOND as u64;
    std::time::Duration::from_millis(millis)
}

/// Escape special characters in TOC strings
fn escape_toc_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[derive(Debug, thiserror::Error)]
pub enum TocError {
    #[error("Failed to write TOC file '{0}': {1}")]
    WriteError(std::path::PathBuf, String),

    #[error("IO error: {0}")]
    IoError(#[from] std::io::Error),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_escape_toc_string() {
        assert_eq!(escape_toc_string("Hello World"), "Hello World");
        assert_eq!(escape_toc_string("Say \"Hi\""), "Say \\\"Hi\\\"");
        assert_eq!(escape_toc_string("Back\\slash"), "Back\\\\slash");
    }
}
